import type { AppProps } from "next/app";
import Head from "next/head";
import "@/styles/globals.css";

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Frontend Interview WIN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://www.win.investments/site-logo.svg" />
      </Head>
      <body>
        <Component {...pageProps} />
      </body>
    </>
  );
};

export default App;
